### ISSUE TITLE
JuMP does not have a dot function

### ISSUE THREAD

**Issue by dhendryc** [chriscoey/PajaritoExtras.jl#4]
Here in line 51 https://github.com/chriscoey/PajaritoExtras.jl/blob/main/src/epipersepspectral/matrix.jl

JuMP does not know the dot function. Just using `dot(R_diag, W_diag)` should work.

**Comment by chriscoey** [comment]
Thanks @dhendryc, JuMP stopped exporting that. fixed in #5
